splitの引数の書き方を修正
mimosa-project/emvscode pull request #49
Opened 2020-11-22 04:41 UTC by fpsbpkm

splitの引数の記述を誤っており，Windows以外で正しく動作していませんでした．
また，ローカルファイルへのハイパーリンクの記法がOSによって異なるため，分岐させています．
仮想環境のUbuntuでは正しく動作することを確認しました．

2020-11-27 00:28 UTC, aabaa requested changes

2020-11-27 00:28 UTC, aabaa commented on src/extension.ts
> +            process.env.PATH = mizfiles + ';' + process.env.PATH;
PATHは先頭にある方が優先されるので，控え目に後ろに置く方が良いです．
```typescript
process.env.PATH = process.env.PATH +  ';' + mizfiles;
```
また，posixではパスの区切り文字がセミコロンではなくコロンになります．ここはwindowsだけ限定で通るコードでしょうか？

2020-11-27 03:06 UTC, fpsbpkm commented on src/extension.ts
> +            process.env.PATH = mizfiles + ';' + process.env.PATH;
>PATHは先頭にある方が優先されるので，控え目に後ろに置く方が良いです．

Windowsはデフォルトで，verifier.exeという同名のドライバ検証ツールが実行できるようで，後ろに追加するとそちらが優先されてしまい，うまく動作しませんでした．
デフォルトのverifier.exeがある場所を調べて，その直前にMIZFILESのパスを追加するなどの処理をした方が良いでしょうか？

> posixではパスの区切り文字がセミコロンではなくコロンになります．ここはwindowsだけ限定で通るコードでしょうか？

すみません，Linuxで動作確認はしましたが，Windows以外でも追加されてしまう状態になっていました．
Windowsのみで処理するよう，以下のような条件に修正しようと思います．
```javascript
 if (String(process.env.PATH).indexOf(mizfiles) === -1 && process.platform === 'win32')
```

2020-11-27 03:11 UTC, aabaa commented on src/extension.ts
> +            process.env.PATH = mizfiles + ';' + process.env.PATH;
> Windowsはデフォルトで，verifier.exeという同名のドライバ検証ツールが実行できるようで，後ろに追加するとそちらが優先されてしまい，うまく動作しませんでした．
> デフォルトのverifier.exeがある場所を調べて，その直前にMIZFILESのパスを追加するなどの処理をした方が良いでしょうか？

ということは，Windowsについてはパスを通すのではなく，verifierはフルパスで指定した方が良いということだと思います．そうしないと次はドライバ検証ツールがデフォルトで動作しなくなるので．

2020-11-27 03:17 UTC, fpsbpkm commented on src/extension.ts
> +            process.env.PATH = mizfiles + ';' + process.env.PATH;
承知しました．
OSで条件分岐を作り，以下のように実装しようと思います．
* Windowsの場合&rarr;コマンドを絶対パスにする
* Mac,Linuxの場合&rarr;パスが通っている前提とする

2020-11-29 13:25 UTC, aabaa approved these changes

2020-11-29 13:25 UTC, merged